### PR TITLE
7/add barcodes guide

### LINKED ISSUE #7: Write guide to purchasing barcodes
Barcodes for inventory must be small and strongly adhesive. They also must be cost-effective.

The best site I have found for barcodes is [My Asset Tag](http://www.myassettag.com/).

### PR DESCRIPTION
**Pull request by AdamVig**
Closes #7.

Depends on #11.

### CODE REVIEW

**Comment by AdamVig** [comment]
😂  this PR is really only two commits, the last two. Sorry for the mess!

**Comment by AdamVig** [comment]
### Retina
image

### iPhone 6 Plus
image

**Review by emroussel — COMMENTED** [review]
Do you think we know enough about those barcodes to add a little more recommendations? Like these would be best for these types of items/usage, those are more resistant, etc.

**Comment by AdamVig** [comment]
Good point. The main differentiator is size, but of the materials, the metal ones seem to be the most resilient, with the nylon ones coming in second place.

I ordered a sampler pack of all the types of labels so that I can give a real testimony to our clients, but for now I will add in some general guidance on which labels you need for different use cases.

**Comment by AdamVig** [comment]
image

Added descriptions! Great call.

**Review by emroussel — APPROVED** [review]

**Pull request merged**
